// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  // Supabase: use DIRECT URL for migrate/introspect (pooler cannot run migrations reliably).
  // App runtime still uses DATABASE_URL in src/config/prisma.ts (often the pooled connection).
  datasource: {
    url: process.env.DIRECT_URL ?? env("DATABASE_URL"),
  },
});
